# Generated by Django 6.0.3 on 2026-03-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bergline_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestlistSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('barriers', 'Barriers'), ('love_sculpture', 'Love Sculpture'), ('garten_door', 'Garten Door'), ('atm', 'ATM'), ('park', 'Park')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('parsed_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestlist_snapshots', to='bergline_messages.parsedmessage')),
            ],
        ),
        migrations.CreateModel(
            name='MainQueueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('snake', 'Snake'), ('concrete_blocks', 'Concrete Blocks'), ('magic_cube', 'Magic Cube'), ('kiosk', 'Kiosk'), ('20m_behind_kiosk', '20m Behind Kiosk'), ('wriezener_karree', 'Wriezener Karree'), ('metro_sign', 'Metro Sign')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('parsed_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_queue_snapshots', to='bergline_messages.parsedmessage')),
            ],
        ),
    ]
