# Generated by Django 6.0.3 on 2026-03-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('reddit', 'Reddit'), ('form', 'Form')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField()),
                ('ai_model', models.CharField(max_length=50)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('queue_location', models.CharField(blank=True, default='', max_length=50)),
                ('queue_location_confidence', models.FloatField(blank=True, null=True)),
                ('queue_type', models.CharField(blank=True, default='', max_length=20)),
                ('queue_speed', models.CharField(blank=True, default='', max_length=20)),
                ('queue_speed_confidence', models.FloatField(blank=True, null=True)),
                ('bouncer_name', models.CharField(blank=True, default='', max_length=255)),
                ('bouncer_name_confidence', models.FloatField(blank=True, null=True)),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='bergline_messages.rawmessage')),
            ],
        ),
    ]
