# Generated by Django 5.2.12 on 2026-03-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField()),
                ('ai_model', models.CharField(max_length=50)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('queue_location', 'Queue Location'), ('queue_speed', 'Queue Speed'), ('bouncer_name', 'Bouncer Name')], max_length=50)),
                ('extracted_value', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bergline_messages.parsedmessage')),
            ],
        ),
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_messages', to='bergline_messages.source')),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='raw_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='bergline_messages.rawmessage'),
        ),
    ]
